img_size: 224
batch_size: 16
num_classes: 4
epochs: 20
lr: 1e-4
train_split: 0.7
val_split: 0.15
test_split: 0.15
dataset_path: "./dataset/Monkeypox Skin Image Dataset/"
classes:
  - Monkeypox
  - Chickenpox
  - Measles
  - Normal
